name: Terraform Apply

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_ssh_key_id: ${{ secrets.TF_VAR_ssh_key_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init -input=false

      - name: Terraform Plan
        id: tfplan
        working-directory: ./terraform
        run: |
          terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: ${{ success() }}
        working-directory: ./terraform
        run: |
          terraform apply -input=false -auto-approve tfplan
